Update gh action to run all tests and publish report.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -26,21 +26,13 @@ jobs:
       run: ./gradlew build
 
     - name: Run tests
-      run: ./gradlew test
+      run: ./gradlew check
 
     - name: Run ktlint
       run: ./gradlew ktlintCheck
 
-    - name: Upload test results
-      uses: actions/upload-artifact@v4
-      if: failure()
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: test-results
-        path: build/reports/tests/
-
-    - name: Upload ktlint results
-      uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: ktlint-results
-        path: build/reports/ktlint/
+        report_paths: '**/build/test-results/*/TEST-*.xml'
